[phases.setup]
commands = [
  "pip install -r requirements.txt"
]

[phases.build]
commands = [
  "python manage.py makemigrations",
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "gunicorn gradHunt.wsgi:application"
]
