export const recentJobs = [
    {
        jobId: 83746,
        position: "Software Developer",
        company_name: "Freshworks",
        location: "Pune, Maharashtra, India",
        salary: "7.2 - 8.4 LPA",
        posted: "10 mins ago",
    },
    {
        jobId: 83426,
        position: "Backend Developer",
        company_name: "Google",
        location: "Bangalore, Karnataka, India",
        salary: "15 - 20 LPA",
        posted: "20 mins ago",
    },
    {
        jobId: 34844,
        position: "Frontend Developer",
        company_name: "Microsoft",
        location: "Hyderabad, Telangana, India",
        salary: "12 - 15 LPA",
        posted: "30 mins ago",
    },
    {
        jobId: 34764,
        position: "Fullstack Developer",
        company_name: "Amazon",
        location: "Chennai, Tamil Nadu, India",
        salary: "10 - 12 LPA",
        posted: "40 mins ago",
    },
    {
        jobId: 73464,
        position: "DevOps Engineer",
        company_name: "Flipkart",
        location: "Mumbai, Maharashtra, India",
        salary: "8 - 10 LPA",
        posted: "50 mins ago",
    },
    {
        jobId: 32743,
        position: "Data Scientist",
        company_name: "IBM",
        location: "Pune, Maharashtra, India",
        salary: "12 - 14 LPA",
        posted: "1 hour ago",
    },
    {
        jobId: 38642,
        position: "ML Engineer",
        company_name: "TCS",
        location: "Kolkata, West Bengal, India",
        salary: "9 - 11 LPA",
        posted: "1 hour 10 mins ago",
    },
    {
        jobId: 23743,
        position: "System Analyst",
        company_name: "Infosys",
        location: "Noida, Uttar Pradesh, India",
        salary: "7 - 9 LPA",
        posted: "1 hour 20 mins ago",
    },
    {
        jobId: 23782,
        position: "Network Engineer",
        company_name: "Wipro",
        location: "Gurgaon, Haryana, India",
        salary: "6 - 8 LPA",
        posted: "1 hour 30 mins ago",
    },
    {
        jobId: 98473,
        position: "Security Engineer",
        company_name: "HCL",
        location: "Chandigarh, India",
        salary: "10 - 12 LPA",
        posted: "1 hour 40 mins ago",
    },
];



export const companyLogo = [
    { company: "company1" },
    { company: "company2" },
    { company: "company3" },
    { company: "company4" },
    { company: "company5" },
    { company: "company6" },
    { company: "company7" },
    { company: "company8" },
    { company: "company9" },
    { company: "company10" },
];