export const companySize = [
    { label: '1 - 9 Employees', value: "1 - 9"},
    { label: '10 - 49 Employees', value: "10 - 49"},
    { label: '50 - 99 Employees', value: "50 - 99"},
    { label: '100 - 249 Employees', value: "100 - 249"},
    { label: 'More than 250 Employees', value: "More than 250"},
];


export const levels = [
	{ label: "Junior Level", value: "Junior Level" },
	{ label: "Mid Level", value: "Mid Level" },
	{ label: "High Level", value: "High Level" },
	{ label: "Top Management", value: "Top Management" },
];

export const experience = [
	{ value: "0", label: "Less than 1 Year" },
	{ value: "1", label: "1+ Year" },
	{ value: "2", label: "2+ Years" },
	{ value: "3", label: "3+ Years" },
	{ value: "4", label: "4+ Years" },
	{ value: "5", label: "5+ Years" },
	{ value: "6", label: "6+ Years" },
	{ value: "7", label: "7+ Years" },
	{ value: "8", label: "8+ Years" },
	{ value: "9", label: "9+ Years" },
	{ value: "10", label: "10+ Years" },
	{ value: "11", label: "11+ Years" },
	{ value: "12", label: "12+ Years" },
	{ value: "13", label: "13+ Years" },
	{ value: "14", label: "14+ Years" },
	{ value: "15", label: "More than 15 Years" },
];

export const sectors = [
	{
		label: "Engineering",
		value: "Engineering",
	},
	{
		label: "Product Engineering",
		value: "Product Engineering",
	},
	{
		label: "Information Technology",
		value: "Information Technology",
	},
	{
		label: "Computer Software",
		value: "Computer Software",
	},
	{
		label: "Computer Hardware",
		value: "Computer Hardware",
	},
	{
		label: "Telecommunications",
		value: "Telecommunications",
	},
	{
		label: "Internet/E-commerce",
		value: "Internet/E-commerce",
	},
	{ label: "Data Analytics", value: "Data Analytics" },
	{ label: "Cybersecurity", value: "Cybersecurity" },
	{ label: "Accounting", value: "Accounting" },
	{ label: "Finance", value: "Finance" },
	{ label: "Banking", value: "Banking" },
	{ label: "Insurance", value: "Insurance" },
	{ label: "Marketing", value: "Marketing" },
	{ label: "Advertising", value: "Advertising" },
	{
		label: "Public Relations",
		value: "Public Relations",
	},
	{ label: "Human Resources", value: "Human Resources" },
	{
		label: "Business Consulting",
		value: "Business Consulting",
	},
	{ label: "Legal Services", value: "Legal Services" },
	{
		label: "Healthcare Services",
		value: "Healthcare Services",
	},
	{ label: "Pharmaceuticals", value: "Pharmaceuticals" },
	{ label: "Biotechnology", value: "Biotechnology" },
	{ label: "Medical Devices", value: "Medical Devices" },
	{ label: "Construction", value: "Construction" },
	{ label: "Architecture", value: "Architecture" },
	{ label: "Engineering", value: "Engineering" },
	{ label: "Manufacturing", value: "Manufacturing" },
	{
		label: "Logistics/Supply Chain",
		value: "Logistics/Supply Chain",
	},
	{ label: "Retail", value: "Retail" },
	{ label: "Hospitality", value: "Hospitality" },
	{ label: "Food Services", value: "Food Services" },
	{ label: "Aviation", value: "Aviation" },
	{ label: "Automotive", value: "Automotive" },
	{ label: "Oil and Gas", value: "Oil and Gas" },
	{ label: "Utilities", value: "Utilities" },
	{
		label: "Renewable Energy",
		value: "Renewable Energy",
	},
	{
		label: "Education Services",
		value: "Education Services",
	},
	{
		label: "Training and Development",
		value: "Training and Development",
	},
	{
		label: "Media/Entertainment",
		value: "Media/Entertainment",
	},
	{ label: "Publishing", value: "Publishing" },
	{ label: "Design Services", value: "Design Services" },
	{ label: "Creative Arts", value: "Creative Arts" },
];

export const functions = [
    {
        label: "Software Development",
        value: "Software Development",
    },
    { label: "Web Development", value: "Web Development" },
    {
        label: "Mobile App Development",
        value: "Mobile App Development",
    },
    { label: "Cloud Computing", value: "Cloud Computing" },
    {
        label: "Artificial Intelligence",
        value: "Artificial Intelligence",
    },
    {
        label: "Machine Learning",
        value: "Machine Learning",
    },
    { label: "Data Science", value: "Data Science" },
    { label: "Cybersecurity", value: "Cybersecurity" },
    {
        label: "Network Administration",
        value: "Network Administration",
    },
    { label: "IT Support", value: "IT Support" },
    {
        label: "Financial Analysis",
        value: "Financial Analysis",
    },
    {
        label: "Investment Banking",
        value: "Investment Banking",
    },
    {
        label: "Audit and Assurance",
        value: "Audit and Assurance",
    },
    { label: "Risk Management", value: "Risk Management" },
    {
        label: "Corporate Finance",
        value: "Corporate Finance",
    },
    {
        label: "Digital Marketing",
        value: "Digital Marketing",
    },
    {
        label: "Social Media Marketing",
        value: "Social Media Marketing",
    },
    {
        label: "Content Marketing",
        value: "Content Marketing",
    },
    { label: "Email Marketing", value: "Email Marketing" },
    {
        label: "Search Engine Optimization",
        value: "Search Engine Optimization",
    },
    {
        label: "Talent Acquisition",
        value: "Talent Acquisition",
    },
    {
        label: "Compensation and Benefits",
        value: "Compensation and Benefits",
    },
    {
        label: "Employee Relations",
        value: "Employee Relations",
    },
    {
        label: "Organizational Development",
        value: "Organizational Development",
    },
    {
        label: "Business Strategy",
        value: "Business Strategy",
    },
    {
        label: "Operations Management",
        value: "Operations Management",
    },
    {
        label: "Project Management",
        value: "Project Management",
    },
    {
        label: "Supply Chain Management",
        value: "Supply Chain Management",
    },
    { label: "Corporate Law", value: "Corporate Law" },
    { label: "Litigation", value: "Litigation" },
    {
        label: "Intellectual Property",
        value: "Intellectual Property",
    },
    { label: "Nursing", value: "Nursing" },
    { label: "Physician", value: "Physician" },
    { label: "Pharmacist", value: "Pharmacist" },
    {
        label: "Medical Technologist",
        value: "Medical Technologist",
    },
    {
        label: "Clinical Research",
        value: "Clinical Research",
    },
    {
        label: "Construction Management",
        value: "Construction Management",
    },
    {
        label: "Civil Engineering",
        value: "Civil Engineering",
    },
    {
        label: "Mechanical Engineering",
        value: "Mechanical Engineering",
    },
    {
        label: "Electrical Engineering",
        value: "Electrical Engineering",
    },
    {
        label: "Industrial Engineering",
        value: "Industrial Engineering",
    },
    {
        label: "Quality Assurance",
        value: "Quality Assurance",
    },
    {
        label: "Manufacturing Engineering",
        value: "Manufacturing Engineering",
    },
]

export const skills = [
	{ label: "Java", value: "Java" },
	{ label: "Python", value: "Python" },
	{ label: "C++", value: "C++" },
	{ label: "JavaScript", value: "JavaScript" },
	{ label: "React", value: "React" },
	{ label: "Angular", value: "Angular" },
	{ label: "Node.js", value: "Node.js" },
	{ label: "AWS", value: "AWS" },
	{ label: "Azure", value: "Azure" },
	{ label: "Google Cloud Platform", value: "Google Cloud Platform" },
	{ label: "Docker", value: "Docker" },
	{ label: "Kubernetes", value: "Kubernetes" },
	{ label: "SQL", value: "SQL" },
	{ label: "NoSQL", value: "NoSQL" },
	{ label: "Tableau", value: "Tableau" },
	{ label: "Power BI", value: "Power BI" },
	{ label: "Cyber Security", value: "Cyber Security" },
	{ label: "Ethical Hacking", value: "Ethical Hacking" },
	{ label: "Network Security", value: "Network Security" },
	{ label: "Financial Modeling", value: "Financial Modeling" },
	{ label: "Valuation", value: "Valuation" },
	{ label: "Mergers and Acquisitions", value: "Mergers and Acquisitions" },
	{ label: "Digital Marketing", value: "Digital Marketing" },
	{ label: "Search Engine Optimization", value: "Search Engine Optimization" },
	{ label: "Social Media Marketing", value: "Social Media Marketing" },
	{ label: "Content Marketing", value: "Content Marketing" },
	{ label: "Email Marketing", value: "Email Marketing" },
	{ label: "Talent Acquisition", value: "Talent Acquisition" },
	{ label: "Compensation and Benefits", value: "Compensation and Benefits" },
	{ label: "HR Analytics", value: "HR Analytics" },
	{ label: "Business Strategy", value: "Business Strategy" },
	{ label: "Operations Management", value: "Operations Management" },
	{ label: "Project Management", value: "Project Management" },
	{ label: "Supply Chain Management", value: "Supply Chain Management" },
	{ label: "Corporate Law", value: "Corporate Law" },
	{ label: "Litigation", value: "Litigation" },
	{ label: "Intellectual Property", value: "Intellectual Property" },
	{ label: "Nursing", value: "Nursing" },
	{ label: "Physician", value: "Physician" },
	{ label: "Pharmacology", value: "Pharmacology" },
	{ label: "Clinical Research", value: "Clinical Research" },
	{ label: "Construction Management", value: "Construction Management" },
	{ label: "Civil Engineering", value: "Civil Engineering" },
	{ label: "Mechanical Engineering", value: "Mechanical Engineering" },
	{ label: "Electrical Engineering", value: "Electrical Engineering" },
	{ label: "Industrial Engineering", value: "Industrial Engineering" },
	{ label: "Quality Assurance", value: "Quality Assurance" },
	{ label: "Manufacturing Engineering", value: "Manufacturing Engineering" },
	{ label: "PHP", value: "PHP" },
	{ label: "Ruby on Rails", value: "Ruby on Rails" },
	{ label: ".NET", value: ".NET" },
	{ label: "Swift", value: "Swift" },
	{ label: "Kotlin", value: "Kotlin" },
	{ label: "React Native", value: "React Native" },
	{ label: "Flutter", value: "Flutter" },
	{ label: "TensorFlow", value: "TensorFlow" },
	{ label: "PyTorch", value: "PyTorch" },
	{
		label: "Natural Language Processing",
		value: "Natural Language Processing",
	},
	{ label: "Computer Vision", value: "Computer Vision" },
	{ label: "Deep Learning", value: "Deep Learning" },
	{
		label: "Machine Learning Engineering",
		value: "Machine Learning Engineering",
	},
	{ label: "Data Visualization", value: "Data Visualization" },
	{ label: "Data Mining", value: "Data Mining" },
	{ label: "Data Warehousing", value: "Data Warehousing" },
	{ label: "Big Data Analytics", value: "Big Data Analytics" },
	{ label: "Hadoop", value: "Hadoop" },
	{ label: "Spark", value: "Spark" },
	{ label: "Ethical Hacking", value: "Ethical Hacking" },
	{ label: "Penetration Testing", value: "Penetration Testing" },
	{ label: "Risk Management", value: "Risk Management" },
	{ label: "Compliance", value: "Compliance" },
	{ label: "Financial Reporting", value: "Financial Reporting" },
	{ label: "Budgeting and Forecasting", value: "Budgeting and Forecasting" },
	{ label: "Tax Planning", value: "Tax Planning" },
	{
		label: "User Experience (UX) Design",
		value: "User Experience (UX) Design",
	},
	{ label: "User Interface (UI) Design", value: "User Interface (UI) Design" },
	{ label: "Graphic Design", value: "Graphic Design" },
	{ label: "Video Editing", value: "Video Editing" },
	{ label: "Adobe Creative Cloud", value: "Adobe Creative Cloud" },
	{ label: "Salesforce", value: "Salesforce" },
	{ label: "SAP", value: "SAP" },
	{ label: "Oracle", value: "Oracle" },
	{ label: "Lean Six Sigma", value: "Lean Six Sigma" },
	{ label: "Agile Methodology", value: "Agile Methodology" },
	{ label: "Scrum", value: "Scrum" },
	{ label: "Kanban", value: "Kanban" },
	{ label: "Contract Law", value: "Contract Law" },
	{ label: "Legal Research", value: "Legal Research" },
	{ label: "Medical Coding", value: "Medical Coding" },
	{ label: "Electronic Health Records", value: "Electronic Health Records" },
	{ label: "Surgical Procedures", value: "Surgical Procedures" },
	{ label: "Structural Engineering", value: "Structural Engineering" },
	{ label: "AutoCAD", value: "AutoCAD" },
	{ label: "3D Modeling", value: "3D Modeling" },
	{ label: "Finite Element Analysis", value: "Finite Element Analysis" },
	{ label: "Lean Manufacturing", value: "Lean Manufacturing" },
	{ label: "Six Sigma", value: "Six Sigma" },
	{ label: "Robotics", value: "Robotics" },
	{
		label: "Programmable Logic Controllers",
		value: "Programmable Logic Controllers",
	},
];
