interface SkillOption {
    value: string;
    label: string;
    image?: string;
    category: string;
}

export const skillObject: SkillOption[] = [
    {
        value: "Git",
        label: "Git",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/git.svg",
        category: "Source Control",
    },
    {
        value: "GitHub",
        label: "GitHub",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/github.svg",
        category: "Source Control",
    },
    {
        value: "GitLab",
        label: "GitLab",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/gitlab.svg",
        category: "Source Control",
    },
    {
        value: "Bitbucket",
        label: "Bitbucket",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/bitbucket.svg",
        category: "Source Control",
    },
    {
        value: "Docker",
        label: "Docker",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/docker.svg",
        category: "DevOps",
    },
    {
        value: "Kubernetes",
        label: "Kubernetes",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/kubernetes.svg",
        category: "DevOps",
    },
    {
        value: "Jenkins",
        label: "Jenkins",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/jenkins.svg",
        category: "DevOps",
    },
    {
        value: "Visual Studio Code",
        label: "Visual Studio Code",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/vscode.svg",
        category: "Tools",
    },
    {
        value: "IntelliJ IDEA",
        label: "IntelliJ IDEA",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/intellij.svg",
        category: "Tools",
    },
    {
        value: "NeoVim",
        label: "NeoVim",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/neovim.svg",
        category: "Tools",
    },
    {
        value: "Vim",
        label: "Vim",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/vim.svg",
        category: "Tools",
    },
    {
        value: "CSS3",
        label: "CSS3",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/css3.svg",
        category: "StyleSheets",
    },
    {
        value: "Sass",
        label: "Sass",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/sass.svg",
        category: "StyleSheets",
    },
    {
        value: "Less",
        label: "Less",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/less.svg",
        category: "StyleSheets",
    },
    {
        value: "Tailwind CSS",
        label: "Tailwind CSS",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/tailwindcss.svg",
        category: "StyleSheets",
    },
    {
        value: "BootStrap",
        label: "BootStrap",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/bootstrap.svg",
        category: "StyleSheets",
    },
    {
        value: "React",
        label: "React",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/react.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Angular",
        label: "Angular",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/angular.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Vue.js",
        label: "Vue.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/vuejs.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "jQuery",
        label: "jQuery",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/jquery.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Node.js",
        label: "Node.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/nodejs.svg",
        category: "Backend Frameworks",
    },
    {
        value: "Express.js",
        label: "Express.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/express.svg",
        category: "Backend Frameworks",
    },
    {
        value: "Ruby on Rails",
        label: "Ruby on Rails",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/rails.svg",
        category: "Backend Frameworks",
    },
    {
        value: "Django",
        label: "Django",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/django.svg",
        category: "Backend Frameworks",
    },
    {
        value: "Django Rest Framework",
        label: "Django Rest Framework",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/djangorestframework.svg",
        category: "Backend Frameworks",
    },
    {
        value: "MySQL",
        label: "MySQL",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/mysql.svg",
        category: "Databases",
    },
    {
        value: "MongoDB",
        label: "MongoDB",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/mongodb.svg",
        category: "Databases",
    },
    {
        value: "PostgreSQL",
        label: "PostgreSQL",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/postgresql.svg",
        category: "Databases",
    },
    {
        value: "AWS",
        label: "AWS",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/aws.svg",
        category: "Cloud",
    },
    {
        value: "Azure",
        label: "Azure",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/azure.svg",
        category: "Cloud",
    },
    {
        value: "Google Cloud",
        label: "Google Cloud",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/googlecloud.svg",
        category: "Cloud",
    },
    {
        value: "JavaScript",
        label: "JavaScript",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/javascript.svg",
        category: "Programming Language",
    },
    {
        value: "Python",
        label: "Python",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/python.svg",
        category: "Programming Language",
    },
    {
        value: "Java",
        label: "Java",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/java.svg",
        category: "Programming Language",
    },
    {
        value: "Redux",
        label: "Redux",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/redux.svg",
        category: "State Management",
    },
    {
        value: "Recoil",
        label: "Recoil",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/recoil.svg",
        category: "State Management",
    },
    {
        value: "Zustand",
        label: "Zustand",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/zustand.svg",
        category: "State Management",
    },
    {
        value: "React Query",
        label: "React Query",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/reactquery.svg",
        category: "State Management",
    },
    {
        value: "GraphQL",
        label: "GraphQL",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/graphql.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "TypeScript",
        label: "TypeScript",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/typescript.svg",
        category: "Programming Language",
    },
    {
        value: "Webpack",
        label: "Webpack",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/webpack.svg",
        category: "Tools",
    },
    {
        value: "Babel",
        label: "Babel",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/babel.svg",
        category: "Tools",
    },
    {
        value: "Firebase",
        label: "Firebase",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/firebase.svg",
        category: "Backend Frameworks",
    },
    {
        value: "DigitalOcean",
        label: "DigitalOcean",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/digitalocean.svg",
        category: "Cloud",
    },
    {
        value: "Go",
        label: "Go",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/go.svg",
        category: "Programming Language",
    },
    {
        value: "Rust",
        label: "Rust",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/rust.svg",
        category: "Programming Language",
    },
    {
        value: "Swift",
        label: "Swift",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/swift.svg",
        category: "Programming Language",
    },
    {
        value: "Kotlin",
        label: "Kotlin",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/kotlin.svg",
        category: "Programming Language",
    },
    {
        value: "Ruby",
        label: "Ruby",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/ruby.svg",
        category: "Programming Language",
    },
    {
        value: "PHP",
        label: "PHP",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/php.svg",
        category: "Programming Language",
    },
    {
        value: "Apache Kafka",
        label: "Apache Kafka",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/kafka.svg",
        category: "Databases",
    },
    {
        value: "Elasticsearch",
        label: "Elasticsearch",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/elasticsearch.svg",
        category: "Databases",
    },
    {
        value: "Redis",
        label: "Redis",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/redis.svg",
        category: "Databases",
    },
    {
        value: "NGINX",
        label: "NGINX",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/nginx.svg",
        category: "Tools",
    },
    {
        value: "Apache",
        label: "Apache",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/apache.svg",
        category: "Tools",
    },
    {
        value: "C++",
        label: "C++",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/cplusplus.svg",
        category: "Programming Language",
    },
    {
        value: "C",
        label: "C",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/c.svg",
        category: "Programming Language",
    },
    {
        value: "Scala",
        label: "Scala",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/scala.svg",
        category: "Programming Language",
    },
    {
        value: "Haskell",
        label: "Haskell",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/haskell.svg",
        category: "Programming Language",
    },
    {
        value: "Elixir",
        label: "Elixir",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/elixir.svg",
        category: "Programming Language",
    },
    {
        value: "Flutter",
        label: "Flutter",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/flutter.svg",
        category: "Mobile Frameworks and Libraries",
    },
    {
        value: "React Native",
        label: "React Native",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/react.svg",
        category: "Mobile Frameworks and Libraries",
    },
    {
        value: "Xamarin",
        label: "Xamarin",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/xamarin.svg",
        category: "Mobile Frameworks and Libraries",
    },
    {
        value: "Ionic",
        label: "Ionic",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/ionic.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Electron",
        label: "Electron",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/electron.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Tauri",
        label: "Tauri",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/tauri.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Next.js",
        label: "Next.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134089/skills/nextjs.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Gatsby",
        label: "Gatsby",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/gatsby.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Ember.js",
        label: "Ember.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/ember.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Backbone.js",
        label: "Backbone.js",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/backbone.svg",
        category: "Frontend Frameworks and Libraries",
    },
    {
        value: "Laravel",
        label: "Laravel",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/laravel.svg",
        category: "Backend Frameworks",
    },

    {
        value: "Apache Airflow",
        label: "Apache Airflow",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/airflow.svg",
        category: "DevOps",
    },
    {
        value: "Terraform",
        label: "Terraform",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/terraform.svg",
        category: "DevOps",
    },
    {
        value: "Ansible",
        label: "Ansible",
        image: "https://res.cloudinary.com/dniezlcfy/image/upload/v1723134060/skills/ansible.svg",
        category: "DevOps",
    },
    {
        value: "Communication",
        label: "Communication",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Teamwork",
        label: "Teamwork",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Time Management",
        label: "Time Management",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Leadership",
        label: "Leadership",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Problem Solving",
        label: "Problem Solving",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Customer Service",
        label: "Customer Service",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Marketing",
        label: "Marketing",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Sales",
        label: "Sales",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Project Management",
        label: "Project Management",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Data Analysis",
        label: "Data Analysis",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Microsoft Office",
        label: "Microsoft Office",
        image: "#",
        category: "Productivity Tools",
    },
    {
        value: "Google Workspace",
        label: "Google Workspace",
        image: "#",
        category: "Productivity Tools",
    },
    {
        value: "Foreign Language",
        label: "Foreign Language",
        image: "#",
        category: "Language Skills",
    },
    {
        value: "Public Speaking",
        label: "Public Speaking",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Writing",
        label: "Writing",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Emotional Intelligence",
        label: "Emotional Intelligence",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Conflict Resolution",
        label: "Conflict Resolution",
        image: "#",
        category: "Soft Skills",
    },
    {
        value: "Negotiation",
        label: "Negotiation",
        image: "#",
        category: "Business Skills",
    },
    {
        value: "Critical Thinking",
        label: "Critical Thinking",
        image: "#",
        category: "Soft Skills",
    },
];
