# Generated by Django 5.0.4 on 2024-04-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('companyLocation', models.CharField(max_length=100)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='app.personaldetails')),
            ],
            options={
                'verbose_name': 'Employment Details',
                'verbose_name_plural': 'Employment Details',
            },
        ),
    ]
