# Generated by Django 5.0.4 on 2024-09-14 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='branches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='companyBanner',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='companyLogo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profilePicture',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
