# Generated by Django 5.0.4 on 2024-06-01 13:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Recruiter Details',
                'verbose_name_plural': 'Recruiter Details',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobileMumber', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User Details',
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='HiringPreference',
            fields=[
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.recruiter')),
                ('experience', models.IntegerField()),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('industry', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('function', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Hiring Preference',
                'verbose_name_plural': 'Hiring Preference',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField()),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobType', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=50), size=None)),
                ('jobDescription', models.TextField()),
                ('companySize', models.CharField(max_length=100)),
                ('skillRequired', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=100), size=None)),
                ('experience', models.CharField(max_length=50)),
                ('postedDate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recruiter')),
            ],
            options={
                'verbose_name': 'Job Postings',
                'verbose_name_plural': 'Job Postings',
            },
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardName', models.CharField(max_length=255)),
                ('yearReceived', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Award',
            },
        ),
        migrations.DeleteModel(
            name='EmploymentDetails',
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
