# Generated by Django 5.0.4 on 2024-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recruiter_userdetails_hiringpreference_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
