# Generated by Django 5.0.4 on 2024-04-13 16:58

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employmentdetails_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='userId',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=7, max_length=15, prefix='user_'),
        ),
    ]
