# Generated by Django 5.0.4 on 2024-04-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personaldetails_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
