# Generated by Django 5.0.4 on 2024-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdetails_resumelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='liveLink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='sourceCodeLink',
            field=models.URLField(blank=True, default=''),
        ),
    ]
