# Generated by Django 5.0.4 on 2024-06-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdetails_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='mobileMumber',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='profilePic',
            new_name='profilePicture',
        ),
    ]
