# Generated by Django 5.0.8 on 2024-10-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_companyprofile_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='revenue',
            new_name='yearlyRevenue',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='addressLine1',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='services',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='values',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='vision',
        ),
    ]
