# Generated by Django 5.0.8 on 2024-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_revenue_companyprofile_yearlyrevenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='isCompanyAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
