# Generated by Django 5.0.4 on 2024-04-14 03:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='userId',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', length=7, max_length=15, prefix='user_', primary_key=True, serialize=False),
        ),
    ]
