# Generated by Django 5.0.4 on 2024-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_livelink_alter_project_sourcecodelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='credentialId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credentialUrl',
            field=models.URLField(max_length=255),
        ),
    ]
