# Generated by Django 5.0.8 on 2024-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userdetails_iscompanyadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
