# Generated by Django 5.0.4 on 2024-04-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_personaldetails_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
