# Generated by Django 5.0.4 on 2024-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_personaldetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='id',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='userID',
            field=models.CharField(default=1234, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
