# Generated by Django 5.0.8 on 2024-10-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_companyprofile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='jobId',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='workType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
