# Generated by Django 5.0.4 on 2024-07-18 07:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_award_options_alter_userdetails_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.recruiter')),
                ('companyLogo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('companyCover', models.ImageField(blank=True, null=True, upload_to='company_cover/')),
                ('companyName', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('employeeSize', models.IntegerField()),
                ('establishedYear', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=200)),
                ('branches', models.CharField(blank=True, max_length=500, null=True)),
                ('about', models.TextField()),
                ('values', models.TextField()),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
