# Generated by Django 5.0.4 on 2024-04-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_personaldetails_id_personaldetails_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='userID',
            new_name='userName',
        ),
    ]
