# Generated by Django 5.0.8 on 2024-10-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_jobpostings_joblocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='postedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
