# Generated by Django 5.0.4 on 2024-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='employeeSize',
            field=models.CharField(max_length=50),
        ),
    ]
