# Generated by Django 5.0.4 on 2024-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_userid_personaldetails_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentdetails',
            options={'verbose_name': 'EmploymentDetails', 'verbose_name_plural': 'EmploymentDetails'},
        ),
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'verbose_name': 'PersonalDetails', 'verbose_name_plural': 'PersonalDetails'},
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='personal_details',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='userName',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
