# Generated by Django 5.0.4 on 2024-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_companyprofile_employeesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='establishedYear',
            field=models.CharField(max_length=6),
        ),
    ]
