# Generated by Django 5.0.8 on 2024-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_jobpostings_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='companySize',
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='applyLink',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
