# Generated by Django 5.0.4 on 2024-07-25 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_companyprofile_establishedyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('startMonth', models.CharField(max_length=20)),
                ('startYear', models.CharField(max_length=4)),
                ('endMonth', models.CharField(blank=True, max_length=20)),
                ('endYear', models.CharField(blank=True, max_length=4)),
                ('jobLocation', models.CharField(max_length=60)),
                ('locationType', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
