# Generated by Django 5.0.4 on 2024-07-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteName', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('startMonth', models.CharField(max_length=20)),
                ('startYear', models.CharField(max_length=4)),
                ('endMonth', models.CharField(max_length=20)),
                ('endYear', models.CharField(max_length=4)),
                ('instituteLocation', models.CharField(max_length=60)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
    ]
