# Generated by Django 5.0.4 on 2024-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='degreeTitle',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='fieldOfStudy',
            new_name='studyField',
        ),
    ]
