# Generated by Django 5.0.8 on 2024-10-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobpostings_requiredskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='skillsRequired',
        ),
    ]
