# Generated by Django 5.0.4 on 2024-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_degree_education_degreetitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='isCurrentlyWorking',
            field=models.BooleanField(default=False),
        ),
    ]
