# Generated by Django 5.0.4 on 2024-04-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_employmentdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='app.personaldetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='userName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
