# Generated by Django 5.0.8 on 2024-10-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_jobpostings_skillsrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='isApplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='applied', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='app.userdetails')),
                ('jobPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.jobpostings')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
