# Generated by Django 5.0.4 on 2024-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
