# Generated by Django 5.0.8 on 2024-10-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_jobpostings_isapplied_jobpostings_issaved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='isApplied',
        ),
    ]
