# Generated by Django 5.0.4 on 2024-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(default='Your mission, should you choose to accept it, is to face your fate', max_length=255),
            preserve_default=False,
        ),
    ]
