# Generated by Django 5.0.8 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_jobpostings_isapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='isApplied',
            field=models.BooleanField(default=False),
        ),
    ]
