# Generated by Django 5.0.4 on 2024-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userdetails_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='clerk_user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
