# Generated by Django 5.0.8 on 2024-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_saved_at_savedjob_savedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='isApplied',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='isSaved',
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='openings',
            field=models.IntegerField(default=1),
        ),
    ]
