# Generated by Django 5.0.4 on 2024-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_userdetails_clerk_user_id_clerkuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='clerk_user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='clerk_user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
