# Generated by Django 5.0.8 on 2024-10-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_jobpostings_isapplied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='salaryRange',
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='currency',
            field=models.CharField(default=500000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='highestSalary',
            field=models.CharField(default=800000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='lowestSalary',
            field=models.CharField(default=1200000, max_length=100),
            preserve_default=False,
        ),
    ]
