# Generated by Django 5.0.8 on 2024-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_jobpostings_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
