# Generated by Django 5.0.8 on 2024-10-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_jobpostings_isarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobPosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostings'),
        ),
    ]
