# Generated by Django 5.0.4 on 2024-08-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateName', models.CharField(max_length=50)),
                ('issuerOrg', models.CharField(max_length=50)),
                ('credentialUrl', models.CharField(max_length=255)),
                ('credentialId', models.CharField(max_length=255)),
                ('isExpirable', models.BooleanField(default=False)),
                ('startMonth', models.CharField(max_length=20)),
                ('startYear', models.CharField(max_length=4)),
                ('endMonth', models.CharField(blank=True, max_length=20, null=True)),
                ('endYear', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
