# Generated by Django 5.0.8 on 2024-11-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_jobapplication_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='isProfilePublic',
            new_name='isProfilePrivate',
        ),
    ]
