# Generated by Django 5.0.8 on 2024-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_isprofilepublic_userdetails_isprofileprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='isProfileActivated',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='isEmailNotificationEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='isWebNotificationEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='plan',
            field=models.CharField(default='free'),
        ),
    ]
