# Generated by Django 5.0.8 on 2024-11-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_userdetails_isprofileactivated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='plan',
            field=models.CharField(default='Free'),
        ),
    ]
