# Generated by Django 5.0.4 on 2024-08-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_award_options_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails'),
        ),
    ]
