# Generated by Django 5.0.8 on 2024-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_userdetails_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='workEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
