# Generated by Django 5.0.8 on 2024-11-18 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_experience_workemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='companySlug',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
