# Generated by Django 5.0.4 on 2024-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_linguistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='companyCover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='companyLogo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profilePicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
