# Generated by Django 5.0.8 on 2024-12-08 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_companyprofile_companyslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='jobCategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
