# Generated by Django 5.0.4 on 2024-09-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_companyprofile_companycover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='companyLocation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_location', to='app.location'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='app.location'),
        ),
    ]
