# Generated by Django 5.0.4 on 2024-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_location_user_remove_recruiter_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='companyLocation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='branches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='instituteLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='jobLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
