# Generated by Django 5.0.4 on 2024-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_recruiter_companylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='companyLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
